name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 


      - name: Build Docker Image
        run: docker build -t riyashukla0803/real-estate-management-system --build-arg REACT_APP_BACKEND_URL='${{secrets.REACT_APP_BACKEND_URL}}' .

      - name: Publish Image to Docker Hub
        run: docker push riyashukla0803/real-estate-management-system:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull riyashukla0803/real-estate-management-system:latest
      - name: delete old container
        run: docker rm -f real-estate-management-system-container

      - name: Run docker Container
        run: "docker run -d -p 5000:5000 --name real-estate-management-system-container -e MONGO_URI=${{secrets.MONGO_URI}} riyashukla0803/real-estate-management-system" 